app:
  GroupId: 1
  NodeManagerAddress: "0x0b8ba57fb7b9e99c233d761f4220c23f35bb5e56"
  UserManagerAddress: "0x2227d6bd260bce55c2ffc0e00e398064f48d1e06"
  ConfigFilePath: "/home/sky/IdeaProjects/github.com/cpucorecore/cs_history/src/main/resources/config.toml"
  FromBlock: "238000"
  ToBlock: "latest"

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/chain_storage?characterEncoding=utf8"
    username: root
    password: MyNewPass5ABC

  jpa:
    hibernate:
      ddl-auto: update
      dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"