app:
  GroupId: 1
  NodeStorageAddress: "0x4a78f4394ca37f5b51c22265fbda26705b0b475d"
  FileStorageAddress: "0x8335a9c6fd7ac5a124bc0b559eb03b1ed3c43e10"
  NodeManagerAddress: "0x92b05522d8728652661c8754492d95fde9fdb1b2"
  UserManagerAddress: "0x2252c9ad8eca38119483b3d02b998d9882b6b400"
  ChainStorageAddress: "0x3ba7b3274a72d0bd233b81fdf22fa8b4d15fc2da"
  ConfigFilePath: "/home/sky/IdeaProjects/github.com/cpucorecore/cs_history/src/main/resources/config.toml"
  FromBlock: "238000"
  ToBlock: "latest"

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/chain_storage?characterEncoding=utf8"
    username: root
    password: MyNewPass5ABC

  jpa:
    hibernate:
      ddl-auto: update
      dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"